name: Build Mac App Bundle

on: 
  push:
    branches: [ main ] 

jobs:
  build-macos:
    runs-on: macos-latest  
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 升级到 v4

      - name: Set up Python
        uses: actions/setup-python@v5 # 升级到 v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyQt6 pyinstaller

      - name: Run PyInstaller
        run: |
          # 请确保 your_script.py 替换为你仓库里真实的 py 文件名
          pyinstaller --noconsole --windowed --onefile --name "QuadrantNote" main.py

      - name: Compress App
        run: |
          cd dist
          zip -r QuadrantNote_Mac.zip QuadrantNote.app

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: My-Mac-App-Result
          # 这里改用通配符，只要是 dist 文件夹里的 zip 全都传上来
          path: dist/*.zip
